server:
  port: 8080
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  main:
    allow-circular-references: true
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=Access-Control-Allow-Origin, *
      globalcors:
        add-to-simple-url-handler-mapping: true
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
  
      discovery:
        locator:
          enabled: true
      routes:
      - id: user-service
        uri: http://localhost:8081
        predicates:
        - Path=/auth/**, /admin/**
        
         
      - id: product-service
        uri: http://localhost:8082
        predicates:
        - Path=/products/**
        
      - id: order-service
        uri: http://localhost:8083
        predicates:
        - Path=/orders/**
        filters:
        - AuthenticationFilter
        
      - id: cart-service
        uri: http://localhost:8084
        predicates:
        - Path=/cart/**
        filters:
        - AuthenticationFilter
         
      - id: wishlist-service
        uri: http://localhost:8085
        predicates:
        - Path=/wishlist/**
        filters:
        - AuthenticationFilter

      - id: discount-service
        uri: http://localhost:8086
        predicates:
        - Path=/discount/**
        
         
        