server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/shop_user
    username: root
    password: Palden1923
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true